<a href="https://colab.research.google.com/github/ekqlsrla/ESAA/blob/main/3%EC%9B%94_11%EC%9D%BC_1%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[파이썬 머신러닝 완벽 가이드 - 03 넘파이]**



> ## 1.넘파이 ndarray 개요

 * 넘파이 array() 함수 : 파이썬의 리스트와 같은 다양한 인자 입력 받아 ndarray로 변환하는 기능 수행, 생성된 ndarray 배열의 shape 변수는 행과 열의 수를 튜플 형태로 가짐
 





In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

## 1차원 array로 3개의 데이터

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ',array2.shape)

## 2차원 array로 2row & 3 col

array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ',array3.shape)

## 2차원 array로 1 row & 3 col

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)





> ## 2. ndarray의 데이터 타입

*  가능한 데이터값 : 숫자, 문자열,불 모두 가능
*  가능한 데이터 타입 : 연산의 특성상 같은 데이터 타입만 가능 
   **=> 한 개의 ndarray객체에 int와 float가 함께 있을 수 없음**



In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64




* 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 **더 큰 데이터 타입**으로 형 변환 일괄 적용



In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)

list3 = [1,2,3.0]
arrat3 = np.array(list3)
print(arrat3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] int64




*   ndarray 내 **데이터값의 타입 변경** : astype() 메서드 이용
    - 메모리를 더 절약해야 할 때 보통 이용


In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32




> ## 3. ndarray를 편리하게 생성하기 - arange,zeros,ones
