<a href="https://colab.research.google.com/github/ekqlsrla/ESAA/blob/main/3%EC%9B%94_11%EC%9D%BC_1%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[파이썬 머신러닝 완벽 가이드 - 03 넘파이]**



> ## 1.넘파이 ndarray 개요

 * 넘파이 array() 함수 : 파이썬의 리스트와 같은 다양한 인자 입력 받아 ndarray로 변환하는 기능 수행, 생성된 ndarray 배열의 shape 변수는 행과 열의 수를 튜플 형태로 가짐
 





In [2]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

## 1차원 array로 3개의 데이터

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ',array2.shape)

## 2차원 array로 2row & 3 col

array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ',array3.shape)

## 2차원 array로 1 row & 3 col

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)





> ## 2. ndarray의 데이터 타입

*  가능한 데이터값 : 숫자, 문자열,불 모두 가능
*  가능한 데이터 타입 : 연산의 특성상 같은 데이터 타입만 가능 
   **=> 한 개의 ndarray객체에 int와 float가 함께 있을 수 없음**



In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64




* 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 **더 큰 데이터 타입**으로 형 변환 일괄 적용



In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)

list3 = [1,2,3.0]
arrat3 = np.array(list3)
print(arrat3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] int64




*   ndarray 내 **데이터값의 타입 변경** : astype() 메서드 이용
    - 메모리를 더 절약해야 할 때 보통 이용


In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32




> ## 3. ndarray를 편리하게 생성하기 - arange,zeros,ones
  : 특정 크기와 차원을 가진 ndarry를 연속값이나 0,1로 초기화해 쉽게 생성해햐 할 필요가 있는 경우


*  arrage() : 파이썬 표준 함수인 **range()** 와 유사한 기능
  - default 함수 인자 : stop 값 => 1차원 ndarray 만들어 줌








In [4]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


 

 *  zeros() : 튜플 형태의 shape값을 입력하면 **모든 값을 0으로 채운** 해당 shape를 가진 ndarray 반환

* ones() : 튜플 형태의 shape값을 입력하면 **모든 값을 1로 채운** 해당 shape를 가진 ndarray 반환
   - default 값 : float 64




In [8]:
zero_array= np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)




> ## 4. ndarray의 차원과 크기를 변경하는 reshape()



*  reshape() : 변환을 원하는 크기를 함수 인자로 부여
1) 인자로 '-1'을 적용하는 경우 : 원래 ndarray와 호환되는 새로운 shape로 변환
  - reshape(-1,1) = > 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray

In [12]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2 : \n',array2)

array3 = array1.reshape(5,2)
print('array3 : \n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape :',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape : ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array3 shape :  (5, 2)


In [22]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarry로 변환
array6 = array1.reshape(-1,1)
print('array6 :\n', array6.tolist()) ## tolist() 메서드를 이용해 리스트 자료형으로 변환
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6 :
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)




> ## 5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

1. **특정한 데이터만 추출** : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
2. **슬라이싱(Slicing)** : 슬라이싱은 연속된 인덱스상의 ndarry를 추출하는 방식. ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작인덱스 ~ 종료 인덱스 -1 위치에 있는 데이터의 ndarray를 반환
3. **팬시 인덱싱(Fancy indexing**) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 잇는 데이터의 ndarray를 반환
4. **불린 인덱싱(Boolean indexing)** : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환



### *  단일값 추출

  1) axis 0 : 로우 방향의 축 / axis 1 : 칼럼 방향의 축





In [25]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [27]:
#1차원과 2차원 ndarray에서의 데이터 접근의 차이는 2차원의 경우 콤마로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근하는 것

array1d = np.arange(start =1,stop=10)
array2d= array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값 : ', array2d[0,0])
print('(row=0,col=1) index 가리키는 값 : ', array2d[0,1])
print('(row=1,col=0) index 가리키는 값 : ', array2d[1,0])
print('(row=2,col=2) index 가리키는 값 : ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값 :  1
(row=0,col=1) index 가리키는 값 :  2
(row=1,col=0) index 가리키는 값 :  4
(row=2,col=2) index 가리키는 값 :  9






### * 슬라이싱 

  :  **':' 기호**를 이용해 연속한 데이터를 슬라이싱해서 추출

1. ';'기호 앞에 **시작 인덱스를 생략**하면 자동으로 **맨 처음 인덱스인 0**으로 간주
2. ';'기호 뒤에 **종료 인덱스를 생략**하면 자동으로 **맨 마지막 인덱스**로 간주
3. ':'기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주



In [28]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [30]:
#1차원 ndarray

array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [34]:
#2차원 ndarray

array1d = np.arange(start = 1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2 , 0:2])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:2,1:]\n',array2d[:2,1:])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]


In [35]:
print(array2d[0]) #2차원에서 뒤에 오는 인덱스를 없애면 로우 축의 첫번째 로우 ndarray 반환
print(array2d[1])

[1 2 3]
[4 5 6]



### * 팬시 인덱싱
  
  : **리스트나 ndarray로 인덱스 집합을 지정**하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식



In [39]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]




### * 불린 인덱싱
 : **조건 필터링과 검색**을 동시에 할 수 있음

 - **Step 1** : array1d > 5 와 같이 ndarray의 필터링 조건을 '[ ]' 안에 기재
 - **Step 2** : False 값은 무시하고 True값에 해당하는 인덱스값만 저장(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것)
 - **Step 3** : 저장된 인덱스 데이터 세트로 ndarray 조회



In [40]:
array1d = np.arange(start=1,stop=10)
#[]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d>5 불린 인덱싱 결과 값 : ', array3)

array1d>5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [42]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])



> ## 6. 행렬의 정렬 - sort()와 argsort()



### *  행렬 정렬
  1) np.sort() : **넘파이**에서 sort()를 호출하는 방식 

  2) ndarray.sort() : **행렬 자체**에서 sort()를 호출하는 방식





In [45]:
org_array = np.array([3,1,9,5])
print('원본 행렬 :', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 :', sort_array1)
print('np,sort() 호출 후 원본 행렬 : ', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 :', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 :', org_array)

원본 행렬 : [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 : [1 3 5 9]
np,sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 : None
org_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


In [46]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [49]:
# 행렬이 2차원 이상일 경우
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d,axis=0)
print('로우 방향으로 정렬 :\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis = 1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

로우 방향으로 정렬 :
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]





### * 정렬된 행렬의 인덱스를 반환하기
 - np.argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환


In [50]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 :', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 : [1 0 3 2]


In [51]:
#내림차순으로 정렬시 원본 행렬의 인덱스
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 :', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스 : [2 3 0 1]


In [52]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 :',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 : ',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 :  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']




> ## 7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기



### * 행렬 내적(행렬 곱) : np.dot()



In [54]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과 :\n', dot_product)

행렬 내적 결과 :
 [[ 58  64]
 [139 154]]




### * 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬



In [56]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬 : \n',transpose_mat)

A의 전치 행렬 : 
 [[1 3]
 [2 4]]
